# Generated by Django 4.1 on 2022-08-31 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("albums", "0002_alter_album_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="album",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
